### ISSUE TITLE
NameError: name 's' is not defined. Did you mean: 'os'?

### ISSUE THREAD

**Issue by pxtyr** [pIlIp-d/PDF-Compressor#2]
Please correct me if I am mistaken but line 174 in pdf_compressor.py:

should be:  `output_path = os.path.join(os.path.abspath(output_path), path[0].split(os.path.sep)[-1])`

**Comment by pIlIp-d** [comment]
Yeah, that's a pretty old variable name, must have overseen it.
It used to be s = os.path.sep. Horrible naming, I know.
Hope that helps.
Philip
